### ISSUE TITLE
New IUS keys and release RPM URL

### ISSUE THREAD

**Issue by carlwgeorge** [saltstack-formulas/ius-formula#2]
IUS has been making some [infrastructure changes](https://github.com/iusrepo/infrastructure/issues/14).  Someone brought this formula to my attention, and I noticed that it's still using the old URLs for the key and release RPM.  Those should be updated as such:

* RHEL/CentOS 6
    * https://repo.ius.io/RPM-GPG-KEY-IUS-6
	* https://repo.ius.io/ius-release-el6.rpm
* RHEL/CentOS 7
	* https://repo.ius.io/RPM-GPG-KEY-IUS-7
	* https://repo.ius.io/ius-release-el7.rpm

**Comment by dseira** [comment]
Updated.
